const products = [
    // Sản phẩm đơn lẻ - Giải đói
    {
        id: 1,
        name: "BÔNG LAN SỐT RUỐC",
        price: 30000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/2.png",
        category: "single",
        description: "Bánh bông lan mềm mịn, thơm phức với lớp sốt ruốc đậm đà, hấp dẫn. Hoàn hảo cho bữa sáng hoặc bữa phụ",
        unit: "cái",
        quantityInputId: "quantity_single1",
        isPopular: true,
    },
    {
        id: 2,
        name: "BÁNH SÂU GÀ",
        price: 30000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/3.png",
        category: "single",
        description: "Bánh sâu giòn rụm với nhân gà tươi ngon, gia vị hài hòa. Món ăn vặt không thể bỏ qua",
        unit: "cái",
        quantityInputId: "quantity_single2",
        isPopular: false,
    },
    {
        id: 3,
        name: "TRÀ THÁI",
        price: 12000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/4.png",
        category: "drink",
        description: "Trà Thái nguyên chất với hương vị đặc trưng, mát lạnh, giải khát tuyệt vời trong ngày hè nóng bức",
        unit: "hộp",
        quantityInputId: "quantity_single3",
        isPopular: true,
    },
    {
        id: 4,
        name: "BÁNH TART TRỨNG",
        price: 10000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/banhtarttrung.png",
        category: "single",
        description: "Bánh tart với lớp kem trứng béo ngậy, vỏ bánh giòn tan. Món ngọt tinh tế cho mọi dịp",
        unit: "cái",
        quantityInputId: "quantity_single4",
        isPopular: false,
    },
    {
        id: 5,
        name: "HOA QUẢ DẦM",
        price: 20000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/5.png",
        category: "dessert",
        description: "Hỗn hợp hoa quả tươi ngon được dầm đường, mát lạnh, bổ dưỡng. Món tráng miệng lý tưởng mùa hè",
        unit: "hộp",
        quantityInputId: "quantity_single5",
        isPopular: true,
    },
    {
        id: 6,
        name: "SỮA ĐẬU NÀNH",
        price: 15000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/6.png",
        category: "drink",
        description: "Sữa đậu nành nguyên chất, không chất bảo quản, giàu protein và vitamin. Thức uống bổ dưỡng cho sức khỏe",
        unit: "chai",
        quantityInputId: "quantity_single6",
        isPopular: false,
    },
    {
        id: 7,
        name: "SỮA CHUA HỘP",
        price: 80000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/7.png",
        category: "dessert",
        description: "Hộp 12 hũ sữa chua nhỏ thơm ngon, chua ngọt vừa phải. Tiện lợi cho cả gia đình thưởng thức",
        unit: "hộp 12 hũ",
        quantityInputId: "quantity_single7",
        isPopular: false,
    },
    {
        id: 8,
        name: "SỮA CHUA TÚI",
        price: 45000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/8.png",
        category: "dessert",
        description: "10 túi sữa chua tiện lợi, dễ mang theo. Vị chua ngọt tự nhiên, bổ sung lợi khuẩn cho đường ruột",
        unit: "10 túi",
        quantityInputId: "quantity_single8",
        isPopular: true,
    },

    // Combo sản phẩm - Best Sale
    {
        id: 9,
        name: "COMBO NGỌT NGÀO 1",
        price: 132000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/9.png",
        category: "combo",
        description: "Combo hoàn hảo gồm: Bông lan sốt ruốc + Bánh sâu gà + Trà Thái + Sữa chua hộp. Đầy đủ dinh dưỡng cho cả ngày",
        unit: "combo",
        quantityInputId: "quantity_combo1",
        isPopular: true,
        originalPrice: 152000,
        discount: "Tiết kiệm 20k",
    },
    {
        id: 10,
        name: "COMBO NGỌT NGÀO 2",
        price: 100000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/12.png",
        category: "combo",
        description: "Combo tiết kiệm với: Bông lan sốt ruốc + Bánh sâu gà + Trà Thái + Sữa chua túi. Ngon miệng, giá hấp dẫn",
        unit: "combo",
        quantityInputId: "quantity_combo2",
        isPopular: true,
        originalPrice: 118000,
        discount: "Tiết kiệm 18k",
    },
    {
        id: 11,
        name: "COMBO THANH MÁT 1",
        price: 117000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/11.png",
        category: "combo",
        description: "Combo mát lạnh gồm: Bông lan sốt ruốc + Bánh tart trứng + Sữa đậu nành + Sữa chua hộp. Tuyệt vời cho mùa hè",
        unit: "combo",
        quantityInputId: "quantity_combo3",
        isPopular: true,
        originalPrice: 135000,
        discount: "Tiết kiệm 18k",
    },
    {
        id: 12,
        name: "COMBO THANH MÁT 2",
        price: 85000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/13.png",
        category: "combo",
        description: "Combo giá rẻ: Bông lan sốt ruốc + Bánh tart trứng + Sữa đậu nành + Sữa chua túi. Phù hợp sinh viên, học sinh",
        unit: "combo",
        quantityInputId: "quantity_combo4",
        isPopular: false,
        originalPrice: 100000,
        discount: "Tiết kiệm 15k",
    },
    {
        id: 13,
        name: "COMBO YÊU THÍCH 1",
        price: 131000,
        image: "https://raw.githubusercontent.com/Trantoan12022004/host_image_page_anhtonton/main/images/gayquymhx2025/10.png",
        category: "combo",
        description: "Combo được yêu thích nhất: Bánh sâu gà + Bánh tart trứng + Hoa quả dầm + Sữa chua hộp. Đa dạng hương vị",
        unit: "combo",
        quantityInputId: "quantity_combo5",
        isPopular: true,
        originalPrice: 140000,
        discount: "Tiết kiệm 9k",
    },
    {
        id: 14,
        name: "COMBO YÊU THÍCH 2",
        price: 99000,
        image: "",
        category: "combo",
        description: "Combo phổ biến: Bánh sâu gà + Bánh tart trứng + Hoa quả dầm + Sữa chua túi. Cân bằng dinh dưỡng, giá tốt",
        unit: "combo",
        quantityInputId: "quantity_combo6",
        isPopular: false,
        originalPrice: 105000,
        discount: "Tiết kiệm 6k",
    },
];

// Xuất dữ liệu để sử dụng trong các file khác
if (typeof module !== "undefined" && module.exports) {
    module.exports = products;
} else {
    window.products = products;
}